feature_list = [
    'p_T Jet1',
    '\eta Jet1',
    '\phi Jet1',
    'E Jet1',
    'b tag Jet1',
    'p_x Jet1',
    'p_y Jet1',
    'p_z Jet1',
    'p_T Jet2',
    '\eta Jet2',      
    '\phi Jet2',    
    'E Jet2',
    'b tag Jet2',
    'p_x Jet2',
    'p_y Jet2',
    'p_z Jet2',
    'p_T Jet3',
    '\eta Jet3',
    '\phi Jet3',
    'E Jet3',
    'b tag Jet3',
    'p_x Jet3',
    'p_y Jet3',
    'p_z Jet3',
    'p_T Jet4',
    '\eta Jet4',
    '\phi Jet4',
    'E Jet4',
    'b tag Jet4',
    'p_x Jet4',
    'p_y Jet4',
    'p_z Jet4',
    'p_T Jet5',
    '\eta Jet5',
    '\phi Jet5',
    'E Jet5',
    'b tag Jet5',
    'p_x Jet5',
    'p_y Jet5',
    'p_z Jet5',
    'p_T Jet6',
    '\eta Jet6',
    '\phi Jet6',
    'E Jet6',
    'b tag Jet6',
    'p_x Jet6',
    'p_y Jet6',
    'p_z Jet6',
    'p_T Jet7',
    '\eta Jet7',
    '\phi Jet7',
    'E Jet7',
    'b tag Jet7',
    'p_x Jet7',
    'p_y Jet7',
    'p_z Jet7',
    '\phi MET',
    'p_x MET',
    'p_y MET',
    'p_z MET',
    'p_T Lepton',
    '\eta Lepton',
    '\phi Lepton',
    'E Lepton',
    'p_x Lepton',
    'p_y Lepton',
    'p_z Lepton'
    
]
